### ISSUE TITLE
I suck at git

### ISSUE THREAD

**Issue by skylermishkin** [skylermishkin/algorithmic-heights#4]
I made a change to my local without pulling first; I was on branch fibo which I believe was previously deleted remotely. I committed my fibo branch changes and pushed to remote. Then I pulled master to my local, and realized I had made a mistake forgetting the file structure was slightly changed in master (util.py). I cascaded down a path of mistakes trying to fix the previous mistake without messing up remote master. Now my local is two commits ahead of master (I added to .gitignore then removed to try and restore), and the fibo branch now does not share the same structure as master. I would like to restore my local master to be as remote and re-create fibo with proper structure so everything can be happy again.

**Comment by mondomishi** [comment]
No worries.  This does however bring up the important point of always keeping an eye on the status of your local repo relative to the remote repo.  But it sounds like you see that.  I too have trouble remembering it sometimes.

Anyways, moving forward, I currently see two main options:
- If the changes aren't too extensive, you can just stash your version of the repo somewhere else on your system, clone a fresh copy of the remote repo, and then properly integrate your changes from the stashed local repo into the fresh local repo, and then push.  That might look something like this:
  
  ``` shell
  # move your local changes onto your desktop temporarily
  mv path/to/repo/algorithmic-heights ~/Desktop/
  # clone a fresh copy of the remote repo onto your system
  cd path/to/repo/
  git clone git@github.com:skylermishkin/algorithmic-heights.git
  # # # # # #
  # this is where you would integrate your changes (from the local repo stashed on desktop) 
  # into this fresh local copy of the repo (and then commit and push them)
  # # # # # #
  # eventually you could then remove the old stashed repo
  rm -rf ~/Desktop/algorithmic-heights
  ```
  
  Note that this is the approach I would probably take.
- Alternatively, you could go through with the merge.  In this case, you are on your own, as I have no idea what you have done and what the merge will look like.  Basically though, you just get the files to the state you want, and then make a commit, and then push.
